export const initialEdges = [
  {
    id: "e1-2",
    source: "1",
    sourceHandle: "right",
    target: "2",
    targetHandle: "left",
    animated: "true",

    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  {
    id: "e2-3",
    source: "2",
    sourceHandle: "right",
    target: "3",
    targetHandle: "left",
    animated: "true",

    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  {
    id: "e3-4",
    source: "3",
    sourceHandle: "right",
    target: "4",
    targetHandle: "left",
    animated: "true",

    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  {
    id: "e4-5",
    source: "4",
    sourceHandle: "right",
    target: "5",
    targetHandle: "left",
    animated: "true",

    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  {
    id: "e3-6",
    source: "3",
    sourceHandle: "right",
    target: "6",
    animated: "true",
    targetHandle: "left",

    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  // {
  //   id: "e6-8",
  //   source: "6",
  //   sourceHandle: "right",
  //   target: "8",
  //   targetHandle: "left",
  //   type: "smoothstep",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "gray", strokeWidth: 2 },
  // },
  {
    id: "e7-8",
    source: "7",
    sourceHandle: "bottom",
    target: "8",
    targetHandle: "top",
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  // {
  //   id: "e7-9",
  //   source: "7",
  //   sourceHandle: "bottom",
  //   target: "9",
  //   targetHandle: "top",
  //   type: "smoothstep",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "gray", strokeWidth: 2 },
  // },
  {
    id: "6-10",
    source: "6",
    sourceHandle: "bottom",
    target: "10",
    targetHandle: "top",
    animated: "true",

    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
  // {
  //   id: "e8-9",
  //   source: "8",
  //   sourceHandle: "bottom",
  //   target: "9",
  //   targetHandle: "top",
  //   type: "smoothstep",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "gray", strokeWidth: 2 },
  // },
  // {
  //   id: "e9-10",
  //   source: "9",
  //   sourceHandle: "bottom",
  //   target: "10",
  //   targetHandle: "top",
  //   type: "smoothstep",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "gray", strokeWidth: 2 },
  // },
  {
    id: "e7-11",
    source: "7",
    sourceHandle: "right",
    target: "11",
    animated: "true",

    targetHandle: "top",
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { stroke: "gray", strokeWidth: 2 },
  },
];
